# Generated by Django 4.2.3 on 2023-07-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WasteNotWizards', '0004_remove_user_is_provider_remove_user_is_receiver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AddField(
            model_name='user',
            name='is_provider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_receiver',
            field=models.BooleanField(default=False),
        ),
    ]
