# Generated by Django 4.2.3 on 2023-07-20 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WasteNotWizards', '0006_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='provider',
        ),
    ]
