# Generated by Django 4.2.3 on 2023-07-20 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WasteNotWizards', '0009_alter_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='posted_by_user',
        ),
    ]
