# Generated by Django 4.2.3 on 2023-07-20 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WasteNotWizards', '0010_rename_user_post_posted_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
