# Generated by Django 4.2.3 on 2023-08-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WasteNotWizards', '0013_rename_location_post_address_remove_user_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reservation_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Reserved', 'Reserved'), ('Closed', 'Closed')], default='Open'),
        ),
        migrations.AddField(
            model_name='post',
            name='reservation_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
