# Generated by Django 4.2.3 on 2023-08-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WasteNotWizards', '0015_reservation_lat_reservation_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='lat',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='long',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
