# Generated by Django 4.2.3 on 2023-08-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WasteNotWizards', '0017_reservation_foodlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
